# Generated by Django 4.2.11 on 2026-08-26 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_sriconfiguration_pointofemission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('document_type', models.CharField(max_length=2)),
                ('environment', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1)),
                ('emission_type', models.CharField(choices=[('1', 'Emisión normal')], default='1', max_length=1)),
                ('establishment', models.CharField(max_length=3)),
                ('emission_point', models.CharField(max_length=3)),
                ('sequential', models.CharField(max_length=9)),
                ('access_key', models.CharField(blank=True, max_length=49, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING', 'Pendiente'), ('GENERATED', 'XML generado'), ('SIGNED', 'Firmado'), ('SENT', 'Enviado'), ('RECEIVED', 'Recibido'), ('AUTHORIZED', 'Autorizado'), ('REJECTED', 'Rechazado'), ('ERROR', 'Error')], default='DRAFT', max_length=20)),
                ('xml', models.TextField(blank=True, null=True)),
                ('authorization_number', models.CharField(blank=True, max_length=49, null=True)),
                ('authorization_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_documents', to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_documents', to='core.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sri_electronic_documents', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento electrónico',
                'verbose_name_plural': 'Documentos electrónicos',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='electronicdocument',
            constraint=models.UniqueConstraint(fields=('company', 'document_type', 'establishment', 'emission_point', 'sequential'), name='unique_sri_electronic_document_number'),
        ),
    ]
