# Generated by Django 4.2.11 on 2026-08-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicdocument',
            name='numeric_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
