# Generated by Django 4.2.11 on 2026-08-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0002_electronicdocument_numeric_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicdocument',
            name='numeric_code',
            field=models.CharField(max_length=8),
        ),
    ]
