# Generated by Django 5.2.17 on 2026-09-04 02:25

import django.core.validators
import django.db.models.deletion
import sri.models.sri_certificate
import sri.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sriconfiguration_pointofemission_and_more'),
        ('sri', '0003_alter_electronicdocument_numeric_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SriCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, storage=sri.storage.SriCertificateStorage(), upload_to=sri.models.sri_certificate.sri_certificate_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['p12', 'pfx'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('subject', models.TextField(blank=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('secret_key', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sri_certificates', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado SRI',
                'verbose_name_plural': 'Certificados SRI',
                'ordering': ['company', '-is_default', '-valid_until'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('company',), name='unique_active_default_sri_certificate_company')],
            },
        ),
    ]
