# Generated by Django 5.2.17 on 2026-09-27 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0005_fiscal_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SriReceptionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En progreso'), ('RECEIVED', 'Recibido'), ('REJECTED', 'Rechazado'), ('UNCERTAIN', 'Resultado incierto'), ('FAILED', 'Fallido')], default='IN_PROGRESS', max_length=20)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('electronic_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reception_attempts', to='sri.electronicdocument')),
            ],
            options={
                'ordering': ['-attempted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SriReceptionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(blank=True, max_length=100, null=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sri.srireceptionattempt')),
            ],
        ),
        migrations.AddIndex(
            model_name='srireceptionattempt',
            index=models.Index(fields=['electronic_document', 'status'], name='sri_attempt_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='srireceptionattempt',
            index=models.Index(fields=['status', 'attempted_at'], name='sri_attempt_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='srireceptionattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['IN_PROGRESS', 'UNCERTAIN'])), fields=('electronic_document',), name='unique_active_sri_reception_attempt'),
        ),
    ]
