# Generated by Django 5.2.17 on 2026-09-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0006_srireceptionattempt_srireceptionmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicdocument',
            name='authorized_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SriAuthorizationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En progreso'), ('AUTHORIZED', 'Autorizado'), ('NOT_AUTHORIZED', 'No autorizado'), ('PENDING', 'Pendiente'), ('UNCERTAIN', 'Resultado incierto'), ('PROTOCOL_ERROR', 'Error de protocolo')], default='IN_PROGRESS', max_length=20)),
                ('access_key', models.CharField(max_length=49)),
                ('environment', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], max_length=1)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_number', models.CharField(blank=True, max_length=49, null=True)),
                ('authorization_date', models.DateTimeField(blank=True, null=True)),
                ('response_environment', models.CharField(blank=True, max_length=32, null=True)),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('electronic_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorization_attempts', to='sri.electronicdocument')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SriAuthorizationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(blank=True, max_length=100, null=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sri.sriauthorizationattempt')),
            ],
        ),
        migrations.AddIndex(
            model_name='sriauthorizationattempt',
            index=models.Index(fields=['electronic_document', 'status'], name='sri_auth_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sriauthorizationattempt',
            index=models.Index(fields=['status', 'started_at'], name='sri_auth_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='sriauthorizationattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('electronic_document',), name='unique_active_sri_authorization_attempt'),
        ),
    ]
