# Generated by Django 5.2.17 on 2026-09-06 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sriconfiguration_pointofemission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SALES', 'Ventas'), ('PURCHASES', 'Compras'), ('INVENTORY', 'Inventario'), ('ACCOUNTING', 'Contabilidad'), ('PRODUCTION', 'Producción'), ('PAYROLL', 'Nómina')], max_length=20)),
                ('requires_detail', models.BooleanField(default=False)),
                ('affects_inventory', models.BooleanField(default=False)),
                ('inventory_behavior', models.CharField(choices=[('NONE', 'No afecta inventario'), ('IN', 'Entrada'), ('OUT', 'Salida'), ('TRANSFER', 'Transferencia'), ('TRANSFORM', 'Transformación')], default='NONE', max_length=20)),
                ('can_issue_electronic', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['category', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('affects_inventory', True), ('inventory_behavior', 'NONE'), _connector='OR'), name='document_type_inventory_behavior_consistent')],
            },
        ),
    ]
