# Generated by Django 5.2.17 on 2026-09-07 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DOCUMENT_TYPE_CODES = (
    ("SAL", "SALES_INVOICE"),
    ("PUR", "PURCHASE_INVOICE"),
    ("TRF", "INVENTORY_TRANSFER"),
)


def backfill_document_type(apps, schema_editor):
    Sequence = apps.get_model("core", "Sequence")
    DocumentType = apps.get_model("core", "DocumentType")
    alias = schema_editor.connection.alias
    for sequence_code, document_type_code in DOCUMENT_TYPE_CODES:
        document_type = DocumentType.objects.using(alias).get(code=document_type_code)
        Sequence.objects.using(alias).filter(
            code=sequence_code, document_type__isnull=True,
        ).update(document_type_id=document_type.pk)


def reverse_backfill_document_type(apps, schema_editor):
    Sequence = apps.get_model("core", "Sequence")
    DocumentType = apps.get_model("core", "DocumentType")
    alias = schema_editor.connection.alias
    for sequence_code, document_type_code in DOCUMENT_TYPE_CODES:
        document_type = DocumentType.objects.using(alias).get(code=document_type_code)
        Sequence.objects.using(alias).filter(
            code=sequence_code, document_type_id=document_type.pk,
        ).update(document_type_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_document_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='core.documenttype'),
        ),
        migrations.RunPython(backfill_document_type, reverse_backfill_document_type),
        migrations.AddConstraint(
            model_name='sequence',
            constraint=models.UniqueConstraint(fields=('company', 'branch', 'document_type'), name='unique_sequence_company_branch_document_type'),
        ),
    ]
