# Generated by Django 5.2.17 on 2026-09-08 01:57

from django.conf import settings
from django.db import migrations, models


LINE_BEHAVIORS = (
    ("SALES_INVOICE", "COMMERCIAL"),
    ("PURCHASE_INVOICE", "COMMERCIAL"),
    ("INVENTORY_TRANSFER", "QUANTITY"),
)


def classify_line_behavior(apps, schema_editor):
    DocumentType = apps.get_model("core", "DocumentType")
    alias = schema_editor.connection.alias
    for code, behavior in LINE_BEHAVIORS:
        DocumentType.objects.using(alias).filter(
            code=code, line_behavior__isnull=True,
        ).update(line_behavior=behavior)
    pending = list(DocumentType.objects.using(alias).filter(
        line_behavior__isnull=True,
    ).order_by("code").values_list("code", flat=True))
    if pending:
        raise RuntimeError(
            "DocumentType sin clasificación explícita de line_behavior: "
            + ", ".join(pending)
        )


def reverse_classify_line_behavior(apps, schema_editor):
    DocumentType = apps.get_model("core", "DocumentType")
    alias = schema_editor.connection.alias
    for code, behavior in LINE_BEHAVIORS:
        DocumentType.objects.using(alias).filter(
            code=code, line_behavior=behavior,
        ).update(line_behavior=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_sequence_legacy_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='line_behavior',
            field=models.CharField(choices=[('NONE', 'Sin líneas'), ('QUANTITY', 'Cantidad'), ('VALUED', 'Valorada'), ('COMMERCIAL', 'Comercial')], max_length=20, null=True),
        ),
        migrations.RunPython(classify_line_behavior, reverse_classify_line_behavior),
        migrations.AlterField(
            model_name='documenttype',
            name='line_behavior',
            field=models.CharField(choices=[('NONE', 'Sin líneas'), ('QUANTITY', 'Cantidad'), ('VALUED', 'Valorada'), ('COMMERCIAL', 'Comercial')], default='NONE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line_behavior', 'NONE'), _negated=True), ('requires_detail', False), _connector='OR'), name='document_type_line_behavior_consistent'),
        ),
    ]
