# Generated by Django 5.2.17 on 2026-09-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
