# Generated by Django 5.2.17 on 2026-09-22 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transfer_movement_pair'),
        ('purchases', '0005_purchase_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_manifest', to='purchases.purchase')),
                ('stock_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_movement_manifest', to='inventory.stockmovement')),
            ],
        ),
    ]
