class DocumentTypeCodes:
    SALES_INVOICE = "SALES_INVOICE"
    PURCHASE_INVOICE = "PURCHASE_INVOICE"
    INVENTORY_TRANSFER = "INVENTORY_TRANSFER"
    INVENTORY_ADJUSTMENT_IN = "INVENTORY_ADJUSTMENT_IN"
    INVENTORY_ADJUSTMENT_OUT = "INVENTORY_ADJUSTMENT_OUT"
