# Generated by Django 5.2.17 on 2026-09-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transfer_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferdetail',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='transferdetail',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='transferdetail',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='transferdetail',
            name='total',
        ),
        migrations.RemoveField(
            model_name='transferdetail',
            name='unit_price',
        ),
    ]
