# Generated by Django 5.2.17 on 2026-09-12 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_document_line_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_movements', to='inventory.stockmovement'),
        ),
    ]
