# Generated by Django 5.2.17 on 2026-09-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryadjustment_inventoryadjustmentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferMovementPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_in_pair', to='inventory.stockmovement')),
                ('out_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_out_pair', to='inventory.stockmovement')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_pairs', to='inventory.transfer')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('out_movement', models.F('in_movement')), _negated=True), name='transfer_pair_distinct_movements')],
            },
        ),
    ]
