# Generated by Django 4.2.11 on 2026-08-21 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('tax_type', models.CharField(choices=[('IVA', 'IVA'), ('ICE', 'ICE'), ('OTHER', 'Otro')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_configuration', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('taxes', models.ManyToManyField(blank=True, related_name='global_configurations', to='catalog.tax')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.tax'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='product_groups', to='catalog.tax'),
        ),
        migrations.AddField(
            model_name='productsubgroup',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='product_subgroups', to='catalog.tax'),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_tax_company_code'),
        ),
    ]
