# Generated by Django 5.2.17 on 2026-10-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tax_taxconfiguration_product_taxes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='tax_category',
            field=models.CharField(blank=True, choices=[('VAT_STANDARD', 'IVA ordinario'), ('VAT_ZERO_RATED', 'IVA tarifa cero'), ('VAT_EXEMPT', 'Exento de IVA'), ('VAT_NOT_SUBJECT', 'No objeto de IVA')], max_length=32, null=True),
        ),
    ]
