# Generated by Django 5.2.17 on 2026-10-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('RUC', 'RUC'), ('CEDULA', 'Cédula'), ('PASSPORT', 'Pasaporte'), ('FOREIGN_ID', 'Identificación del exterior')], max_length=20, null=True),
        ),
    ]
