# Generated by Django 5.2.17 on 2026-10-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('people', '0002_person_identification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPersonAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'person'), name='people_company_person_access_unique')],
            },
        ),
    ]
