# Generated by Django 5.2.17 on 2026-09-22 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transfer_movement_pair'),
        ('sales', '0005_salesreturn_salesreturndetail_salesreturndetailtax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_manifest', to='sales.sale')),
                ('stock_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_movement_manifest', to='inventory.stockmovement')),
            ],
        ),
    ]
