# Generated by Django 5.2.17 on 2026-09-23 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transfer_movement_pair'),
        ('sales', '0006_salemovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturnMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_manifest', to='sales.salesreturn')),
                ('stock_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_movement_manifest', to='inventory.stockmovement')),
            ],
        ),
    ]
