# Generated by Django 5.2.17 on 2026-10-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesreturnmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NON_FINANCIAL', 'Sin sistema financiero'), ('DEBT_OFFSET', 'Compensación de deudas'), ('DEBIT_CARD', 'Tarjeta de débito'), ('ELECTRONIC_MONEY', 'Dinero electrónico'), ('PREPAID_CARD', 'Tarjeta prepago'), ('CREDIT_CARD', 'Tarjeta de crédito'), ('FINANCIAL_OTHER', 'Otro medio financiero'), ('TITLE_ENDORSEMENT', 'Endoso de títulos')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='saledetailtax',
            name='tax_category',
            field=models.CharField(blank=True, choices=[('VAT_STANDARD', 'IVA ordinario'), ('VAT_ZERO_RATED', 'IVA tarifa cero'), ('VAT_EXEMPT', 'Exento de IVA'), ('VAT_NOT_SUBJECT', 'No objeto de IVA')], max_length=32, null=True),
        ),
    ]
